# 项目信息
site_name: 夜之向日葵
site_url: https://sxp-simon.github.io/HelianNuits/
site_author: Helian Nuits
site_description: 夜之向日葵，此曲为一切不合时宜者而作。

# 代码仓库信息
repo_name: HelianNuits
repo_url: https://github.com/SXP-Simon/HelianNuits
edit_uri: edit/main/docs/

# 版权信息
copyright: Copyright &copy; 2025 ~ now | HelianNuits

hooks:
- material/overrides/hooks/hooks.py

# 主题配置
theme:
  name: material
  language: zh
  logo: assets/HelianNuits.jpg
  favicon: assets/HelianNuits.jpg
  features:
  - announce.dismiss
  - content.code.copy
  - content.code.annotate
  - content.code.select
  - content.tooltips
  - content.action.edit
  - content.action.view
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - toc.integrate
  - header.autohide
  - footer
  palette:
  - media: "(prefers-color-scheme)"
    scheme: slate
    primary: orange
    accent: deep orange
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: orange
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: orange
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  font:
    text: stzhongsong
    code: JetBrains Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
    edit: fontawesome/solid/pen-to-square
    view: fontawesome/solid/eye
    repo: fontawesome/brands/github
    search: fontawesome/solid/magnifying-glass
    top: fontawesome/solid/chevron-up
    menu: fontawesome/solid/bars
    link: fontawesome/solid/link
    download: fontawesome/solid/download
    check: fontawesome/solid/check
    warning: fontawesome/solid/exclamation-triangle
    info: fontawesome/solid/info-circle
    note: fontawesome/solid/sticky-note
    tip: fontawesome/solid/lightbulb
    bug: fontawesome/solid/bug
    example: fontawesome/solid/flask
    quote: fontawesome/solid/quote-left
    abstract: fontawesome/solid/list-ul
    success: fontawesome/solid/check-circle
    failure: fontawesome/solid/times-circle
    question: fontawesome/solid/question-circle
    danger: fontawesome/solid/skull-crossbones
    error: fontawesome/solid/times-octagon
    help: fontawesome/solid/circle-question
    important: fontawesome/solid/exclamation-circle
    caution: fontawesome/solid/triangle-exclamation

# 插件配置
plugins:
- rss:
    match_path: blog/posts/.*\.md$
    categories:
    - categories
    - tags
- search:
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- minify:
    minify_html: true

# 导航配置
nav:
- 首页: index.md
- 关于: about.md
- 主题演示: theme-demo.md
- 博客:
  - 博客首页: blog/index.md
  - 文章列表:
    - 25暑假初期学习规划: blog/posts/25暑假初期学习规划.md
    - ContextMenuForWindows11: blog/posts/ContextMenuForWindows11.md
    - jyyos-ostep-startup: blog/posts/jyyos-ostep-startup.md
    - ncu-inn-stack: blog/posts/ncu-inn-stack.md
    - sample_cn: blog/posts/sample_cn.md
    - 【Narcissus】一段灿烂的故事: blog/posts/【Narcissus】一段灿烂的故事.md
    - 四月是你的谎言: blog/posts/四月是你的谎言.md
    - 天空充满了不安的言语: blog/posts/天空充满了不安的言语.md
    - 科目一启动: blog/posts/科目一启动.md
    - 竭尽全力成为矢志不渝之愚者: blog/posts/竭尽全力成为矢志不渝之愚者.md
    - 近月2官中来袭: blog/posts/近月2官中来袭.md
- OS: blog/sections/OS.md
- 分类: blog/categories.md
- 归档: blog/archive.md

# not_in_nav: |
#   /blog/posts/

# Markdown 扩展
markdown_extensions:
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
    title: 目录
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.emoji:
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
    emoji_index: !!python/name:material.extensions.emoji.twemoji
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.tabbed:
    alternate_style: true
    combine_header_slug: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- pymdownx.caret
- pymdownx.details
- pymdownx.escapeall:
    hardbreak: true
    nbsp: true
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.striphtml:
    strip_comments: true
    strip_js_on_attributes: true
- pymdownx.tilde

extra_javascript:
- javascripts/mathjax.js
- javascripts/sunflower-effects.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
- stylesheets/extra.css
- stylesheets/sunflower-theme.css

# 额外配置项
extra:
  generator: false
  social:
  - icon: simple/github
    link: https://github.com/SXP-Simon
  - icon: simple/bilibili
    link: https://space.bilibili.com/609923881
  - icon: material/email
    link: Nighthelianthus@email.ncu.edu.cn
  - icon: simple/zhihu
    link: https://www.zhihu.com/people/29-79-68-57-27
