# 项目信息
site_name: 夜之向日葵
site_url: https://sxp-simon.github.io/HelianNuits/
site_author: Helian Nuits
site_description: 夜之向日葵，此曲为一切不合时宜者而作。

# 代码仓库信息
repo_name: HelianNuits
repo_url: https://github.com/SXP-Simon/HelianNuits

# 版权信息
copyright: Copyright &copy; 2025 ~ now | HelianNuits

hooks:
  - material/overrides/hooks/hooks.py

# 主题配置
theme:
  name: material
  language: zh
  logo: assets/HelianNuits.jpg
  favicon: assets/HelianNuits.jpg
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tooltips
    - content.action.edit
    - content.action.view
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - toc.integrate
    - header.autohide
    - footer
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: stzhongsong
    code: JetBrains Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
    edit: fontawesome/solid/pen-to-square
    view: fontawesome/solid/eye
    repo: fontawesome/brands/github
    search: fontawesome/solid/magnifying-glass
    top: fontawesome/solid/chevron-up
    menu: fontawesome/solid/bars
    link: fontawesome/solid/link
    download: fontawesome/solid/download
    check: fontawesome/solid/check
    warning: fontawesome/solid/exclamation-triangle
    info: fontawesome/solid/info-circle
    note: fontawesome/solid/sticky-note
    tip: fontawesome/solid/lightbulb
    bug: fontawesome/solid/bug
    example: fontawesome/solid/flask
    quote: fontawesome/solid/quote-left
    abstract: fontawesome/solid/list-ul
    success: fontawesome/solid/check-circle
    failure: fontawesome/solid/times-circle
    question: fontawesome/solid/question-circle
    danger: fontawesome/solid/skull-crossbones
    error: fontawesome/solid/times-octagon
    help: fontawesome/solid/circle-question
    important: fontawesome/solid/exclamation-circle
    caution: fontawesome/solid/triangle-exclamation

# 插件配置
plugins:
  - rss:
      match_path: blog/posts/.*\.md$
      categories:
        - categories
        - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      post_url_date_format: yyyy/MM
      blog_toc: true
  - tags
  - minify:
      minify_html: true
  - i18n:
      languages:
        - locale: zh   # attention
          name: 简体中文
          build: true
          default: true
        - locale: en
          name: English
          build: true  # attention

# 导航配置
nav:
  - 首页: index.md
  - 关于: about.md
  - 博客: blog/index.md
  - 分类: blog/categories.md
  - 归档: blog/archive.md

# Markdown 扩展
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: 目录
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# 额外配置项
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/SXP-Simon
    - icon: simple/bilibili
      link: https://space.bilibili.com/609923881
    - icon: material/email
      link: Nighthelianthus@email.ncu.edu.cn