# 项目信息
site_name: 夜之向日葵
site_url: https://sxp-simon.github.io/HelianNuits/
site_author: Helian Nuits
site_description: 夜之向日葵，此曲为一切不合时宜者而作。

# 代码仓库信息
repo_name: HelianNuits
repo_url: https://github.com/SXP-Simon/HelianNuits

# 版权信息
copyright: Copyright &copy; 2025 ~ now | HelianNuits

hooks:
  - material/overrides/hooks/hooks.py

# 主题配置
theme:
  name: material
  language: zh
  logo: assets/HelianNuits.jpg
  favicon: assets/HelianNuits.jpg
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: stzhongsong
    code: JetBrains Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag

# 插件配置
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      post_url_date_format: yyyy/MM
  - tags
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true

# 导航配置
nav:
  - 首页: index.md
  - 关于: about.md
  - 博客:
     - blog/index.md

# Markdown 扩展
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# 额外配置项
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/SXP-Simon
    - icon: simple/bilibili
      link: https://space.bilibili.com/609923881
    - icon: material/email
      link: Nighthelianthus@email.ncu.edu.cn