name: ci
on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:       
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-minify-plugin
          pip install mkdocs-i18n
          pip install mkdocs-markdownextradata-plugin
          pip install Pygments
          pip install pymdown-extensions
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force